set(CTEST_PROJECT_NAME "Solitare Solver Unit Tests")
set(CTEST_DROP_METHOD "http")
set(CTEST_DROP_SITE "localhost:8080")
set(CTEST_DROP_LOCATION "/submit.php?project=SolitareSolverUnitTests")
set(CTEST_DROP_SITE_CDASH TRUE)
