version: '3.3'
services:
  cdash:
    image: "kitware/cdash"
    depends_on:
      - db
    links:
      - db
    ports:
     - "8080:80"
    environment:
      CDASH_ROOT_ADMIN_PASS: $CDASH_ROOT_PASS
      CDASH_STATIC_USERS: |
        ADMIN admin@example.org $CDASH_ADMIN_PASS
          Admin User
      CDASH_CONFIG: |
        $$CDASH_DB_NAME = '$DATABASE_NAME';
        $$CDASH_DB_LOGIN = '$DATABASE_USERNAME';
        $$CDASH_DB_PASS = '$DATABASE_PASSWORD';
        $$CDASH_DB_HOST = 'db';
        $$CDASH_BASE_URL = 'http://localhost:8080';
        $$CDASH_USE_HTTPS = '0';
        $$CDASH_SERVER_NAME = 'localhost:8080';
        $$CDASH_LOG_LEVEL = 'LOG_DEBUG';
  db:
    image: mysql:5-debian
    environment:
      MYSQL_ROOT_PASSWORD: $DATABASE_PASSWORD
      MYSQL_USER: $DATABASE_USERNAME
      MYSQL_PASSWORD: $DATABASE_PASSWORD
      MYSQL_DATABASE: $DATABASE_NAME
      MYSQL_ROOT_HOST: '%'
  adminer:
    image: adminer
    ports: ["8081:8080"]

volumes:
  db-data: { driver: local }
